### ISSUE TITLE
Crash when used with what-is-it-really-used-for

### ISSUE THREAD

**Issue by TehFreek** [SereneRebel/factorio_plc#1]
The following results when the WIIRUF window is closed:

    Error while running event plc::on_gui_closed (ID 84)
    __plc__/control.lua:440: attempt to index field '?' (a nil value)

**Comment by SereneRebel** [comment]
What version of WIIRUF are you using?

**Comment by TehFreek** [comment]
I can't seem to reproduce this any more. Oh well.
